resource_types:
  - name: pull-request
    type: registry-image
    source:
      repository: jtarchie/pr
  - name: slack-notification
    type: registry-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest
  - name: s3-sync
    type: registry-image
    source:
      # Use a form of 18fgsa/s3-resource-simple that provides additional features
      repository: phillbaker/s3-resource-simple
      tag: params

resources:
  - name: designsystem-pr
    type: pull-request
    source:
      access_token: {{github_access_token}}
      private_key: {{github_designsystem_private_key}}
      repo: narmi/design_system
      uri: git@github.com:narmi/design_system.git

  - name: banking-master-image
    type: docker-image
    source:
      repository: 848180528913.dkr.ecr.us-east-1.amazonaws.com:443/banking
      aws_access_key_id: {{aws_access_key}}
      aws_secret_access_key: {{aws_secret_key}}
      max_concurrent_downloads: 3

test_design_system: &test_design_system
  path: bash
  args:
    - -xce
    - |
      cd design_system
      npm ci --loglevel=warn
      npm run test

check_latest_dist: &check_latest_dist
  path: bash
  args:
    - -xce
    - |
      cd design_system
      npm ci --loglevel=warn
      BEFORE=`md5sum dist/index.js`
      npm run build
      AFTER=`md5sum dist/index.js`
      if [[ $BEFORE != $AFTER ]]; then
        echo "PR does not contain latest dist!"
        exit 1
      fi
      echo "MD5sums match, exiting success"

jobs:

  - name: pr-run-tests
    max_in_flight: 5
    build_logs_to_retain: 1000
    plan:
      - aggregate:
        - get: designsystem-pr
          params:
            depth: 1
          trigger: true
          version: every
        - get: banking-master-image
      - put: designsystem-pr
        params:
          path: designsystem-pr
          status: pending
          context: design-system-tests
      - task: test
        timeout: 20m
        image: banking-master-image
        config:
          platform: linux
          caches:
            - path: "$HOME/.npm"
          inputs:
            - name: designsystem-pr
              path: design_system
          run: *test_design_system
        on_success:
          put: designsystem-pr
          params:
            path: designsystem-pr
            status: success
            context: design-system-tests
        on_failure:
          put: designsystem-pr
          params:
            path: designsystem-pr
            status: failure
            context: design-system-tests

  - name: pr-latest-dist
    max_in_flight: 5
    build_logs_to_retain: 1000
    plan:
      - aggregate:
        - get: designsystem-pr
          params:
            depth: 1
          trigger: true
          version: every
        - get: banking-master-image
      - put: designsystem-pr
        params:
          path: designsystem-pr
          status: pending
          context: latest-dist
      - task: check-md5
        timeout: 20m
        image: banking-master-image
        config:
          platform: linux
          caches:
            - path: "$HOME/.npm"
          inputs:
            - name: designsystem-pr
              path: design_system
          run: *check_latest_dist
        on_success:
          put: designsystem-pr
          params:
            path: designsystem-pr
            status: success
            context: latest-dist
        on_failure:
          put: designsystem-pr
          params:
            path: designsystem-pr
            status: failure
            context: latest-dist
