name: Check Build
on: [push]
jobs:
  Build-design_system:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cp -r dist candidate_dist
      - run: npm install

      - name: Check build matches pr
        run: |
              BUILD=$(diff -qr dist candidate_dist)
