name: Check Build
on: [pull_request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
        uses: actions/checkout@v2
      - run: npm install
      - run: npm run build
