name: Publish Storybook
on: [push]
jobs:
  Build-design_system:
    runs-on: ubuntu-latest
    steps:
      - name: Unlock secrets
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          echo "token: $CHROMATIC_PROJECT_TOKEN"
          cd storybook
          npm ci --loglevel=warn
          npm run chromatic
