name: Publish Storybook
on: [push]
jobs:
  Build-design_system:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Unlock secrets
        env:
         CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          cd storybook
          npm ci --loglevel=warn
          npm run chromatic