name: Publish Storybook
on: [push]
jobs:
  Build-design_system:
    runs-on: ubuntu-latest
    steps:
      - uses: secrethub/actions/env-export@v0.2.1
        env:
          CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
      - name: Check out repository code
        uses: actions/checkout@v2
        env:
          CHROMATIC_PROJECT_TOKEN: "${{ secrets.CHROMATIC_PROJECT_TOKEN }}"
      - run: |
          echo "token: $CHROMATIC_PROJECT_TOKEN"
          cd storybook
          npm ci --loglevel=warn
          npm run chromatic
