name: Publish Storybook
on: [push]
jobs:
  Build-design_system:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Unlock secrets
        env:
         CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        run: |
          chmod +x node_modules/.bin/build-storybook
          cd storybook
          npm ci --loglevel=warn
          npm run chromatic